# SPDX-FileCopyrightText: 2021 The NGI Pointer Secure-Scuttlebutt Team of 2020/2021
#
# SPDX-License-Identifier: CC0-1.0

version: '3'
services:
  ssb-go-room:
    build: .
    command: 'sh start.sh'
    env_file: .env
    ports:
      -  "3000:3000" # Proxypass this port through NGINX or Apache as your HTTP landing & dashboard page
      - "0.0.0.0:8008:8008" # This is the port SSB clients connect to
    volumes:
      - ssb-go-room-secrets:/.ssb-go-room-secrets

volumes:
 ssb-go-room-secrets:
